-- sadrzaj tabela sa varchar primarnim kljucevima se ne bi trebao modifikovati
-- tu su da se izbjegne koristenje triggera za umetanje istih informacija o tipovima svaki put kad se radi insert nad tabelom (muy neefikasno)

INSERT INTO tipovi_kartica
VALUES ('DEBK', 'Debitna kartica');
INSERT INTO tipovi_kartica
VALUES ('KRED', 'Kreditna kartica');
INSERT INTO tipovi_kartica
VALUES ('STUD', 'Studentska kartica');
INSERT INTO tipovi_kartica
VALUES ('STED', 'Stedna kartica');

SELECT * FROM tipovi_kartica;
ALTER TABLE tipovi_kartica READ ONLY; -- mfw postoji kljucna rijec za to

INSERT INTO tipovi_racuna
VALUES ('TEKUCI', 1000, 5);
INSERT INTO tipovi_racuna
VALUES ('STEDNI', 100000000, 0);

-- u sustini stedni racun nema limita, on bi trebao biti jednak balansu racuna
-- to se da rijesiti triggerom
-- mada je tesko vjerovatno da ce neko imati potrebu da podigne vise od 100 miliona

SELECT * FROM tipovi_racuna;
ALTER TABLE tipovi_racuna READ ONLY;

INSERT INTO tipovi_kredita
VALUES('HIPO', 300000, 100, 1, 15, 'Hipotekarni kredit', 0.06);
INSERT INTO tipovi_kredita
VALUES('SRED', 100000, 100, 1, 5, 'Srednjorocni kredit', 0.08);
INSERT INTO tipovi_kredita
VALUES('DUGO', 200000, 100, 1, 10, 'Dugorocni kredit', 0.06);
INSERT INTO tipovi_kredita
VALUES('MIKRO', 10000, 100, 1, 3, 'Mikrokredit', 0.1);

SELECT * FROM tipovi_kredita;
ALTER TABLE tipovi_kredita READ ONLY;

-- poslovnice

INSERT INTO poslovnice VALUES(1, 'centralna', 'New York', 10000000, NULL);
INSERT INTO poslovnice VALUES(1, 'regionalna', 'Toronto', 100000, 1);
INSERT INTO poslovnice VALUES(1, 'regionalna', 'Frankfurt', 100000, 1);
INSERT INTO poslovnice VALUES(1, 'regionalna', 'Barcelona', 100000, 1);
INSERT INTO poslovnice VALUES(1, 'regionalna', 'Oslo', 100000, 1);
INSERT INTO poslovnice VALUES(1, 'regionalna', 'Ljubljana', 100000, 1);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Sarajevo', 10000, 6);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Zagreb', 10000, 6);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Budapest', 10000, 6);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Stockholm', 10000, 5);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Reykjavik', 10000, 5);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Copenhagen', 10000, 5);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Toulouse', 10000, 4);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Amsterdam', 10000, 3);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Ottawa', 10000, 2);
INSERT INTO poslovnice VALUES(1, 'lokalna', 'Vancouver', 10000, 2);

SELECT * FROM poslovnice;

-- zaposleni

INSERT INTO zaposleni VALUES(1, 'Una', 'Stubbs', 'risk manager', 'finansijsko trziste', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Rupert', 'Graves', 'analiticar', 'finansijsko trziste', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Louise', 'Brealey', 'kontrolor', 'finansijsko trziste', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Mark', 'Gatiss', 'sef odjela', 'finansijsko trziste', 1, 2000);
INSERT INTO zaposleni VALUES(1, 'Andrew', 'Scott', 'referent', 'unutrasnji platni promet', 1, 1500);
INSERT INTO zaposleni VALUES(1, 'Amanda', 'Abbington', 'sef odjela', 'unutrasnji platni promet', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Jonathan', 'Aris', 'referent', 'pravni odjel', 1, 1500);
INSERT INTO zaposleni VALUES(1, 'Vinette', 'Robinson', 'sef odjela', 'pravni odjel', 1, 1800);
INSERT INTO zaposleni VALUES(1, 'Tanya', 'Moodie', 'blagajnik', 'rad s pravnim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Lindsay', 'Duncan', 'likvidator', 'rad s pravnim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'David', 'Nellist', 'kontrolor', 'rad s pravnim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Simon', 'Kunz', 'sef odjela', 'rad s pravnim licima', 1, 1500);
INSERT INTO zaposleni VALUES(1, 'Timothy', 'Carlton', 'direktor', 'menadzment', 1, 2500);
INSERT INTO zaposleni VALUES(1, 'Wanda', 'Ventham', 'blagajnik', 'rad s fizickim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Lisa', 'McAllister', 'likvidator', 'rad s fizickim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Zoe', 'Telford', 'kontrolor', 'rad s fizickim licima', 1, 1200);
INSERT INTO zaposleni VALUES(1, 'Paul', 'Chequer', 'sef odjela', 'rad s fizickim licima', 1, 1800);
INSERT INTO zaposleni VALUES(1, 'Lara', 'Pulver', 'sistem administrator', 'IT', 1, 1500);
INSERT INTO zaposleni VALUES(1, 'Ed', 'Birch', 'referent', 'pravni odjel', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Phil', 'Davis', 'sef odjela', 'pravni odjel', 2, 1500);
INSERT INTO zaposleni VALUES(1, 'Lars', 'Mikkelsen', 'direktor', 'menadzment', 2, 2000);
INSERT INTO zaposleni VALUES(1, 'Gemma', 'Chan', 'blagajnik', 'rad s fizickim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Zawe', 'Ashton', 'likvidator', 'rad s fizickim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Al', 'Weaver', 'kontrolor', 'rad s fizickim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Russel', 'Tovey', 'sef odjela', 'rad s fizickim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Bertie', 'Carvel', 'blagajnik', 'rad s pravnim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Siobhan', 'Hewlett', 'likvidator', 'rad s pravnim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Joseph', 'Long', 'kontrolor', 'rad s pravnim licima', 2, 1200);
INSERT INTO zaposleni VALUES(1, 'Amelia', 'Bullmore', 'sef odjela', 'rad s pravnim licima', 2, 1500);
INSERT INTO zaposleni VALUES(1, 'Katherine', 'Parkinson', 'sistem administrator', 'IT', 2, 1500);
INSERT INTO zaposleni VALUES(1, 'Danny', 'Webb', 'referent', 'pravni odjel', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Toby', 'Jones', 'sef odjela', 'pravni odjel', 3, 1800);
INSERT INTO zaposleni VALUES(1, 'Matthew', 'Needham', 'direktor', 'menadzment', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Daniel', 'Percival', 'blagajnik', 'rad s fizickim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Andrew', 'Havill', 'likvidator', 'rad s fizickim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Clive', 'Mantle', 'kontrolor', 'rad s fizickim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Kemal', 'Sylvester', 'sef odjela', 'rad s fizickim licima', 3, 1800);
INSERT INTO zaposleni VALUES(1, 'Victoria', 'Wicks', 'blagajnik', 'rad s pravnim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Todd', 'Boyce', 'lkvidator', 'rad s pravnim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'David', 'Fynn', 'kontrolor', 'rad s pravnim licima', 3, 1200);
INSERT INTO zaposleni VALUES(1, 'Alistair', 'Petrie', 'sef odjela', 'rad s pravnim licima', 3, 1800);
INSERT INTO zaposleni VALUES(1, 'Sascha', 'Dhawan', 'sistem administrator', 'IT', 3, 1500);
INSERT INTO zaposleni VALUES(1, 'San', 'Shella', 'referent', 'pravni odjel', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Sasha', 'Behar', 'sef odjela', 'pravni odjel', 4, 1800);
INSERT INTO zaposleni VALUES(1, 'Oona', 'Chaplin', 'direktor', 'menadzment', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Alice', 'Lowe', 'blagajnik', 'rad s fizickim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Sheron', 'Rooney', 'likvidator', 'rad s fizickim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Georgina', 'Rylance', 'kontrolor', 'rad s fizickim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Marcia', 'Warren', 'sef odjela', 'rad s fizickim licima', 4, 1800);
INSERT INTO zaposleni VALUES(1, 'Janice', 'Acquah', 'blagajnik', 'rad s pravnim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'James', 'Duncan', 'lkvidator', 'rad s pravnim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Deborah', 'Moore', 'kontrolor', 'rad s pravnim licima', 4, 1200);
INSERT INTO zaposleni VALUES(1, 'Richard', 'Cunningham', 'sef odjela', 'rad s pravnim licima', 4, 1800);
INSERT INTO zaposleni VALUES(1, 'Tony', 'Pitts', 'sistem administrator', 'IT', 4, 1500);
INSERT INTO zaposleni VALUES(1, 'Will', 'Sharpe', 'referent', 'pravni odjel', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Tomi', 'May', 'sef odjela', 'pravni odjel', 5, 1800);
INSERT INTO zaposleni VALUES(1, 'Catherine', 'MyCormack', 'direktor', 'menadzment', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Eleanor', 'Matsuura', 'blagajnik', 'rad s fizickim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Jack', 'Bence', 'likvidator', 'rad s fizickim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Lauren', 'Crace', 'kontrolor', 'rad s fizickim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Ruth', 'Everett', 'sef odjela', 'rad s fizickim licima', 5, 1800);
INSERT INTO zaposleni VALUES(1, 'Jaye', 'Griffiths', 'blagajnik', 'rad s pravnim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Rosemary', 'Smith', 'lkvidator', 'rad s pravnim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Stephen', 'Wight', 'kontrolor', 'rad s pravnim licima', 5, 1200);
INSERT INTO zaposleni VALUES(1, 'Oliver', 'Lansley', 'sef odjela', 'rad s pravnim licima', 5, 1800);
INSERT INTO zaposleni VALUES(1, 'Rick', 'Warden', 'sistem administrator', 'IT', 5, 1500);
INSERT INTO zaposleni VALUES(1, 'Tim', 'McInnerny', 'referent', 'pravni odjel', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Gina', 'Bramhill', 'sef odjela', 'pravni odjel', 6, 1800);
INSERT INTO zaposleni VALUES(1, 'Nicholas', 'Gadd', 'direktor', 'menadzment', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Syrus', 'Lowe', 'blagajnik', 'rad s fizickim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'John', 'Macmillan', 'likvidator', 'rad s fizickim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Ian', 'Hallard', 'kontrolor', 'rad s fizickim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Gordon', 'Kennedy', 'sef odjela', 'rad s fizickim licima', 6, 1800);
INSERT INTO zaposleni VALUES(1, 'Simon', 'Thorp', 'blagajnik', 'rad s pravnim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Trixiebell', 'Harrowell', 'lkvidator', 'rad s pravnim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Natasha', 'OKeeffe', 'kontrolor', 'rad s pravnim licima', 6, 1200);
INSERT INTO zaposleni VALUES(1, 'Richard', 'Crehan', 'sef odjela', 'rad s pravnim licima', 6, 1800);
INSERT INTO zaposleni VALUES(1, 'Gabrielle', 'Glaister', 'sistem administrator', 'IT', 6, 1500);
INSERT INTO zaposleni VALUES(1, 'Martin', 'Savage', 'referent', 'pravni odjel', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Katy', 'Maw', 'sef odjela', 'pravni odjel', 7, 1800);
INSERT INTO zaposleni VALUES(1, 'Olivia', 'Poulet', 'direktor', 'menadzment', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Caroline', 'Trowbridge', 'blagajnik', 'rad s fizickim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Anthony', 'Cozens', 'likvidator', 'rad s fizickim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Malcolm', 'Rennie', 'kontrolor', 'rad s fizickim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Kevin', 'Trainor', 'sef odjela', 'rad s fizickim licima', 7, 1800);
INSERT INTO zaposleni VALUES(1, 'Lovelace', 'Akpojaro', 'blagajnik', 'rad s pravnim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Calvin', 'Demba', 'lkvidator', 'rad s pravnim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Jalaal', 'Hartley', 'kontrolor', 'rad s pravnim licima', 7, 1200);
INSERT INTO zaposleni VALUES(1, 'Tim', 'Barlow', 'sef odjela', 'rad s pravnim licima', 7, 1800);
INSERT INTO zaposleni VALUES(1, 'Harry', 'Gostelow', 'sistem administrator', 'IT', 7, 1500);
INSERT INTO zaposleni VALUES(1, 'Ralph', 'Ineson', 'referent', 'pravni odjel', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Katy', 'Wix', 'sef odjela', 'pravni odjel', 8, 1800);
INSERT INTO zaposleni VALUES(1, 'Paul', 'Albertson', 'direktor', 'menadzment', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Jacqueline', 'Chan', 'blagajnik', 'rad s fizickim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Munir', 'Khairdin', 'likvidator', 'rad s fizickim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Rosalind', 'Knight', 'kontrolor', 'rad s fizickim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Sydney', 'Wade', 'sef odjela', 'rad s fizickim licima', 8, 1800);
INSERT INTO zaposleni VALUES(1, 'Jim', 'Conway', 'blagajnik', 'rad s pravnim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Tim', 'Wallers', 'lkvidator', 'rad s pravnim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Gerald', 'Kyd', 'kontrolor', 'rad s pravnim licima', 8, 1200);
INSERT INTO zaposleni VALUES(1, 'Charles', 'Edwards', 'sef odjela', 'rad s pravnim licima', 8, 1800);
INSERT INTO zaposleni VALUES(1, 'Matthew', 'Romain', 'sistem administrator', 'IT', 8, 1500);
INSERT INTO zaposleni VALUES(1, 'Rita', 'Davies', 'referent', 'pravni odjel', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Pradeep', 'Jey', 'sef odjela', 'pravni odjel', 9, 1800);
INSERT INTO zaposleni VALUES(1, 'Sarah', 'Lam', 'direktor', 'menadzment', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Nathan', 'Harmer', 'blagajnik', 'rad s fizickim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Edward', 'Holtom', 'likvidator', 'rad s fizickim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Sam', 'Jones', 'kontrolor', 'rad s fizickim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Nicole', 'Arumugam', 'sef odjela', 'rad s fizickim licima', 9, 1800);
INSERT INTO zaposleni VALUES(1, 'Helen', 'Bradbury', 'blagajnik', 'rad s pravnim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Glen', 'Davies', 'lkvidator', 'rad s pravnim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Daniel', 'Fearn', 'kontrolor', 'rad s pravnim licima', 9, 1200);
INSERT INTO zaposleni VALUES(1, 'Vijay', 'Doshi', 'sef odjela', 'rad s pravnim licima', 9, 1800);
INSERT INTO zaposleni VALUES(1, 'Tam', 'Mutu', 'sistem administrator', 'IT', 9, 1500);
INSERT INTO zaposleni VALUES(1, 'Amanda', 'Root', 'referent', 'pravni odjel', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Di', 'Bocher', 'sef odjela', 'pravni odjel', 10, 1800);
INSERT INTO zaposleni VALUES(1, 'Gillian', 'Elisa', 'direktor', 'menadzment', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Imogen', 'Slaughter', 'blagajnik', 'rad s fizickim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Chipo', 'Chung', 'likvidator', 'rad s fizickim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Paul', 'Leonard', 'kontrolor', 'rad s fizickim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Luke', 'Newberry', 'sef odjela', 'rad s fizickim licima', 10, 1800);
INSERT INTO zaposleni VALUES(1, 'Alfred', 'Enoch', 'blagajnik', 'rad s pravnim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'David', 'Gant', 'lkvidator', 'rad s pravnim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Brigid', 'Zengeni', 'kontrolor', 'rad s pravnim licima', 10, 1200);
INSERT INTO zaposleni VALUES(1, 'Stephanie', 'Hyam', 'sef odjela', 'rad s pravnim licima', 10, 1800);
INSERT INTO zaposleni VALUES(1, 'Ben', 'Abell', 'sistem administrator', 'IT', 10, 1500);
INSERT INTO zaposleni VALUES(1, 'Rob', 'Callender', 'referent', 'pravni odjel', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Clare', 'Foster', 'sef odjela', 'pravni odjel', 11, 1800);
INSERT INTO zaposleni VALUES(1, 'Stefan', 'Pejic', 'direktor', 'menadzment', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'John', 'Sessions', 'blagajnik', 'rad s fizickim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Christopher', 'Hunter', 'likvidator', 'rad s fizickim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Darell', 'Quevas', 'kontrolor', 'rad s fizickim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Tim', 'Chipping', 'sef odjela', 'rad s fizickim licima', 11, 1800);
INSERT INTO zaposleni VALUES(1, 'Robin', 'Sebastian', 'blagajnik', 'rad s pravnim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Matthew', 'Wilson', 'lkvidator', 'rad s pravnim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Damian', 'Samuels', 'kontrolor', 'rad s pravnim licima', 11, 1200);
INSERT INTO zaposleni VALUES(1, 'Brett', 'Allen', 'sef odjela', 'rad s pravnim licima', 11, 1800);
INSERT INTO zaposleni VALUES(1, 'Stefano', 'Braschi', 'sistem administrator', 'IT', 11, 1500);
INSERT INTO zaposleni VALUES(1, 'Louise', 'Breckon-Richards', 'referent', 'pravni odjel', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Philip', 'Starnier', 'sef odjela', 'pravni odjel', 12, 1800);
INSERT INTO zaposleni VALUES(1, 'Rosalind', 'Halstead', 'direktor', 'menadzment', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Tony', 'Way', 'blagajnik', 'rad s fizickim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Will', 'Keen', 'likvidator', 'rad s fizickim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Louis', 'Oliver', 'kontrolor', 'rad s fizickim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Charles', 'Furness', 'sef odjela', 'rad s fizickim licima', 12, 1800);
INSERT INTO zaposleni VALUES(1, 'Lee', 'Knight', 'blagajnik', 'rad s pravnim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Rhys', 'Rusbatch', 'lkvidator', 'rad s pravnim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Richard', 'Syms', 'kontrolor', 'rad s pravnim licima', 12, 1200);
INSERT INTO zaposleni VALUES(1, 'Jeany', 'Spark', 'sef odjela', 'rad s pravnim licima', 12, 1800);
INSERT INTO zaposleni VALUES(1, 'Lorraine', 'Hilton', 'sistem administrator', 'IT', 12, 1500);
INSERT INTO zaposleni VALUES(1, 'Peter', 'Pedrero', 'referent', 'pravni odjel', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Ritu', 'Arya', 'sef odjela', 'pravni odjel', 13, 1800);
INSERT INTO zaposleni VALUES(1, 'David', 'Newman', 'direktor', 'menadzment', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Asheq', 'Akhtar', 'blagajnik', 'rad s fizickim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Neal', 'Barry', 'likvidator', 'rad s fizickim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Paul', 'Weller', 'kontrolor', 'rad s fizickim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Alison', 'Lintott', 'sef odjela', 'rad s fizickim licima', 13, 1800);
INSERT INTO zaposleni VALUES(1, 'Samantha', 'Bennett', 'blagajnik', 'rad s pravnim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Derren', 'Brown', 'lkvidator', 'rad s pravnim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Georgina', 'Rich', 'kontrolor', 'rad s pravnim licima', 13, 1200);
INSERT INTO zaposleni VALUES(1, 'Richard', 'Sutton', 'sef odjela', 'rad s pravnim licima', 13, 1800);
INSERT INTO zaposleni VALUES(1, 'Sharon', 'Cherry Ballard', 'sistem administrator', 'IT', 13, 1500);
INSERT INTO zaposleni VALUES(1, 'Edward', 'Judge', 'referent', 'pravni odjel', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Tom', 'Stoughton', 'sef odjela', 'pravni odjel', 14, 1800);
INSERT INTO zaposleni VALUES(1, 'Haydn', 'Gwynne', 'direktor', 'menadzment', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Stanley', 'Townsend', 'blagajnik', 'rad s fizickim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Peter', 'Basham', 'likvidator', 'rad s fizickim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Ilana', 'Kneafsey', 'kontrolor', 'rad s fizickim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Katherine', 'Jakeways', 'sef odjela', 'rad s fizickim licima', 14, 1800);
INSERT INTO zaposleni VALUES(1, 'Wendy', 'Wason', 'blagajnik', 'rad s pravnim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Ben', 'Crowe', 'lkvidator', 'rad s pravnim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Andrew', 'Bone', 'kontrolor', 'rad s pravnim licima', 14, 1200);
INSERT INTO zaposleni VALUES(1, 'Miranda', 'Hennessy', 'sef odjela', 'rad s pravnim licima', 14, 1800);
INSERT INTO zaposleni VALUES(1, 'Aaron', 'Richards', 'sistem administrator', 'IT', 14, 1500);
INSERT INTO zaposleni VALUES(1, 'Edward', 'Judge', 'referent', 'pravni odjel', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Tom', 'Stoughton', 'sef odjela', 'pravni odjel', 15, 1800);
INSERT INTO zaposleni VALUES(1, 'Peter', 'Basham', 'direktor', 'menadzment', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Eiry', 'Thomas', 'blagajnik', 'rad s fizickim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Douglas', 'Wilmer', 'likvidator', 'rad s fizickim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Aleksandar', 'Mikic', 'kontrolor', 'rad s fizickim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'David', 'Colbourn', 'sef odjela', 'rad s fizickim licima', 15, 1800);
INSERT INTO zaposleni VALUES(1, 'Hattie', 'Ladbury', 'blagajnik', 'rad s pravnim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Francesco', 'Rochira', 'lkvidator', 'rad s pravnim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Lasco', 'Atkins', 'kontrolor', 'rad s pravnim licima', 15, 1200);
INSERT INTO zaposleni VALUES(1, 'Gillian', 'Steventon', 'sef odjela', 'rad s pravnim licima', 15, 1800);
INSERT INTO zaposleni VALUES(1, 'Laura', 'Dale', 'sistem administrator', 'IT', 15, 1500);

SELECT * FROM zaposleni;

-- bankomati

INSERT INTO bankomati VALUES(1, 3000, 1);
INSERT INTO bankomati VALUES(1, 3000, 1);
INSERT INTO bankomati VALUES(1, 3000, 2);
INSERT INTO bankomati VALUES(1, 3000, 3);
INSERT INTO bankomati VALUES(1, 2500, 4);
INSERT INTO bankomati VALUES(1, 2500, 5);
INSERT INTO bankomati VALUES(1, 2500, 6);
INSERT INTO bankomati VALUES(1, 2500, 7);
INSERT INTO bankomati VALUES(1, 2500, 8);
INSERT INTO bankomati VALUES(1, 2500, 9);
INSERT INTO bankomati VALUES(1, 2500, 10);
INSERT INTO bankomati VALUES(1, 2500, 11);
INSERT INTO bankomati VALUES(1, 2500, 12);
INSERT INTO bankomati VALUES(1, 2500, 13);
INSERT INTO bankomati VALUES(1, 2500, 14);
INSERT INTO bankomati VALUES(1, 2500, 15);

SELECT * FROM bankomati;

-- musterije

INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kevin', 'Spacey', To_Date('4/25/1965', 'mm/dd/yyyy'), 'zaposlen', 3000, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Robin', 'Wright', To_Date('7/8/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Michael', 'Kelly', To_Date('11/29/1979', 'mm/dd/yyyy'), 'zaposlen', 1100, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Nathan', 'Darrow', To_Date('8/10/1986', 'mm/dd/yyyy'), 'zaposlen', 1600, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Derek', 'Cecil', To_Date('4/1/1983', 'mm/dd/yyyy'), 'zaposlen', 1400, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Lamont', 'Easter', To_Date('3/20/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Molly', 'Parker', To_Date('2/20/1985', 'mm/dd/yyyy'), 'zaposlen', 1500, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Michel', 'Gill', To_Date('8/28/1984', 'mm/dd/yyyy'), 'zaposlen', 1500, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Marla', 'Aaron Wapner', To_Date('9/29/1985', 'mm/dd/yyyy'), 'zaposlen', 1600, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jayne', 'Atkinson', To_Date('1/9/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 1);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Elizabeth', 'Marvel', To_Date('10/15/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Gary', 'Ayash', To_Date('6/21/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Rachel', 'Brosnahan', To_Date('7/28/1990', 'mm/dd/yyyy'), 'zaposlen', 1900, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Lindsay', 'Dyan Epp', To_Date('9/21/1966', 'mm/dd/yyyy'), 'zaposlen', 200, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Sakina', 'Jaffrey', To_Date('7/7/1985', 'mm/dd/yyyy'), 'zaposlen', 1500, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Larry', 'Pine', To_Date('2/22/1979', 'mm/dd/yyyy'), 'zaposlen', 1100, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Curtiss', 'Cook', To_Date('1/16/1977', 'mm/dd/yyyy'), 'zaposlen', 900, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Gregory', 'Divers', To_Date('5/1/1987', 'mm/dd/yyyy'), 'zaposlen', 1700, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'Wells', To_Date('8/15/1990', 'mm/dd/yyyy'), 'zaposlen', 1900, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kristen', 'Connolly', To_Date('11/28/1984', 'mm/dd/yyyy'), 'zaposlen', 1500, 2);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Sebastian', 'Arcelus', To_Date('4/11/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jimmi', 'Simpson', To_Date('2/19/1996', 'mm/dd/yyyy'), 'zaposlen', 2300, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Gerald', 'McRaney', To_Date('3/29/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Reg', 'Cathey', To_Date('6/7/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Paul', 'Sparks', To_Date('6/4/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kate', 'Mara', To_Date('8/17/1988', 'mm/dd/yyyy'), 'zaposlen', 1800, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Boris', 'McGiver', To_Date('12/23/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Reed', 'Birney', To_Date('3/3/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Neve', 'Campbell', To_Date('3/8/1966', 'mm/dd/yyyy'), 'zaposlen', 100, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Elizabeth', 'Norment', To_Date('11/21/1988', 'mm/dd/yyyy'), 'zaposlen', 1800, 3);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Constance', 'Zimmer', To_Date('7/14/1974', 'mm/dd/yyyy'), 'zaposlen', 700, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Corey', 'Stoll', To_Date('1/9/1969', 'mm/dd/yyyy'), 'zaposlen', 300, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Julian', 'Gamble', To_Date('11/4/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Nini', 'Huynh', To_Date('7/21/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Antoinette', 'Montgomery', To_Date('8/17/1968', 'mm/dd/yyyy'), 'zaposlen', 300, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Mozhan', 'Marno', To_Date('6/20/1985', 'mm/dd/yyyy'), 'zaposlen', 1500, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jeremy', 'Holm', To_Date('11/27/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Dave', 'Ferrier', To_Date('6/21/1992', 'mm/dd/yyyy'), 'zaposlen', 2000, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jeremy', 'McLain', To_Date('3/4/1985', 'mm/dd/yyyy'), 'zaposlen', 1500, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Sandrine', 'Holt', To_Date('3/10/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 4);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'Rue', To_Date('7/25/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Andrew', 'Polk', To_Date('8/28/1977', 'mm/dd/yyyy'), 'zaposlen', 1000, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kate', 'Sheil', To_Date('4/25/1995', 'mm/dd/yyyy'), 'zaposlen', 2300, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Draaco', 'Aventura', To_Date('10/22/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Joel', 'Kinnaman', To_Date('2/10/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kim', 'Dickens', To_Date('2/9/1979', 'mm/dd/yyyy'), 'zaposlen', 1100, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Eisa', 'Davis', To_Date('11/6/1983', 'mm/dd/yyyy'), 'zaposlen', 1400, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Mercedes', 'Herrero', To_Date('6/21/1981', 'mm/dd/yyyy'), 'zaposlen', 1200, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Robert', 'Poletick', To_Date('5/29/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Peter', 'Muggleworth', To_Date('2/15/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 5);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Loretta', 'Burnette', To_Date('11/13/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kristi', 'Faye', To_Date('5/1/1979', 'mm/dd/yyyy'), 'zaposlen', 1100, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Dominique', 'MyElligott', To_Date('12/1/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ben', 'Daniels', To_Date('4/3/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Damian', 'Young', To_Date('6/21/1992', 'mm/dd/yyyy'), 'zaposlen', 2000, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Joanna', 'Going', To_Date('3/7/1967', 'mm/dd/yyyy'), 'zaposlen', 200, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Benito', 'Martinez', To_Date('4/12/1979', 'mm/dd/yyyy'), 'zaposlen', 1100, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Joanna', 'Lewis', To_Date('6/24/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Peter', 'Chiamardas', To_Date('3/9/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('David', 'Eichenbaum', To_Date('8/14/1992', 'mm/dd/yyyy'), 'zaposlen', 2100, 6);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Felix', 'Stevenson', To_Date('3/29/1970', 'mm/dd/yyyy'), 'zaposlen', 400, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Andrea', 'Leigh', To_Date('12/20/1973', 'mm/dd/yyyy'), 'zaposlen', 700, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('James', 'Krehely', To_Date('6/23/1983', 'mm/dd/yyyy'), 'zaposlen', 1400, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jody', 'Matzer', To_Date('11/8/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Chrislene', 'Bright', To_Date('6/28/1988', 'mm/dd/yyyy'), 'zaposlen', 1800, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Terry', 'Chen', To_Date('10/7/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Colm', 'Feore', To_Date('8/17/1996', 'mm/dd/yyyy'), 'zaposlen', 2400, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ellen', 'Burstyn', To_Date('1/9/1984', 'mm/dd/yyyy'), 'zaposlen', 1400, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kathleen', 'Chalfant', To_Date('2/5/1996', 'mm/dd/yyyy'), 'zaposlen', 2300, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Shawn', 'Doyle', To_Date('1/18/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 7);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Alexander', 'Sokovikov', To_Date('3/29/1978', 'mm/dd/yyyy'), 'zaposlen', 1000, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ian', 'Blackman', To_Date('7/29/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'Henry Cox', To_Date('2/28/1967', 'mm/dd/yyyy'), 'zaposlen', 200, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Libby', 'Woodbridge', To_Date('6/7/1991', 'mm/dd/yyyy'), 'zaposlen', 2000, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Tawny', 'Cypress', To_Date('5/7/1978', 'mm/dd/yyyy'), 'zaposlen', 1000, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Julie', 'Mun', To_Date('8/14/1996', 'mm/dd/yyyy'), 'zaposlen', 2300, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Sam', 'Page', To_Date('10/28/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Tim', 'Pabon', To_Date('6/7/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Suzanne', 'Savoy', To_Date('4/28/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Finn', 'Douglas', To_Date('4/25/1990', 'mm/dd/yyyy'), 'zaposlen', 1900, 8);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Tony', 'Moore', To_Date('10/13/1969', 'mm/dd/yyyy'), 'zaposlen', 400, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Brian', 'Foreman', To_Date('7/5/1993', 'mm/dd/yyyy'), 'zaposlen', 2100, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'Peddie', To_Date('10/6/1968', 'mm/dd/yyyy'), 'zaposlen', 300, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Matthew', 'Bernard', To_Date('1/22/1967', 'mm/dd/yyyy'), 'zaposlen', 200, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Andre', 'Faulcon', To_Date('1/9/1977', 'mm/dd/yyyy'), 'zaposlen', 900, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Lisa', 'Hamilton', To_Date('3/16/1993', 'mm/dd/yyyy'), 'zaposlen', 2100, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Dan', 'Ziskie', To_Date('2/9/1969', 'mm/dd/yyyy'), 'zaposlen', 300, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kelly', 'AuCoin', To_Date('8/3/1976', 'mm/dd/yyyy'), 'zaposlen', 900, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Gil', 'Birmingham', To_Date('1/29/1977', 'mm/dd/yyyy'), 'zaposlen', 900, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Karl', 'Kenzler', To_Date('6/14/1966', 'mm/dd/yyyy'), 'zaposlen', 200, 9);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Chuck', 'Cooper', To_Date('3/12/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jenna', 'Stern', To_Date('6/6/1991', 'mm/dd/yyyy'), 'zaposlen', 2000, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Daisy', 'Tahan', To_Date('4/14/1977', 'mm/dd/yyyy'), 'zaposlen', 900, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Michael', 'Warner', To_Date('7/21/1990', 'mm/dd/yyyy'), 'zaposlen', 1900, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Dave', 'Quay', To_Date('12/14/1991', 'mm/dd/yyyy'), 'zaposlen', 2000, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Isabelle', 'McNally', To_Date('8/5/1995', 'mm/dd/yyyy'), 'zaposlen', 2300, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kathryn', 'Browning', To_Date('3/8/1992', 'mm/dd/yyyy'), 'zaposlen', 2000, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Neal', 'McNeil', To_Date('6/17/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Chuck', 'Taber', To_Date('4/26/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ashley', 'James', To_Date('5/6/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 10);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Catalina', 'Parks', To_Date('6/25/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Valerie', 'Grace', To_Date('10/28/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Monica', 'Haynes', To_Date('5/18/1983', 'mm/dd/yyyy'), 'zaposlen', 1400, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Johnna', 'Leary', To_Date('5/12/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Mark', 'Salas', To_Date('11/21/1983', 'mm/dd/yyyy'), 'zaposlen', 1400, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Heidi', 'Segal', To_Date('4/18/1992', 'mm/dd/yyyy'), 'zaposlen', 2000, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Cicely', 'Tyson', To_Date('3/4/1977', 'mm/dd/yyyy'), 'zaposlen', 900, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jonathan', 'Hogan', To_Date('6/27/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jeremy', 'Bobb', To_Date('11/27/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Al', 'Sapienza', To_Date('11/7/1993', 'mm/dd/yyyy'), 'zaposlen', 2100, 11);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Francie', 'Swift', To_Date('5/10/1966', 'mm/dd/yyyy'), 'zaposlen', 100, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Wass', 'Stevens', To_Date('11/5/1971', 'mm/dd/yyyy'), 'zaposlen', 500, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Wendy', 'Moniz', To_Date('2/26/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('David', 'Pittu', To_Date('11/15/1987', 'mm/dd/yyyy'), 'zaposlen', 1700, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Chance', 'Kelly', To_Date('11/3/1987', 'mm/dd/yyyy'), 'zaposlen', 1700, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ben', 'Hyland', To_Date('9/25/1974', 'mm/dd/yyyy'), 'zaposlen', 800, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kevin', 'Kilner', To_Date('3/17/1970', 'mm/dd/yyyy'), 'zaposlen', 400, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Maryann', 'Plunkett', To_Date('6/2/1981', 'mm/dd/yyyy'), 'zaposlen', 1200, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Carolyn', 'Smith', To_Date('10/30/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Charles', 'Borland', To_Date('4/15/1993', 'mm/dd/yyyy'), 'zaposlen', 2100, 12);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Michael', 'Park', To_Date('8/29/1972', 'mm/dd/yyyy'), 'zaposlen', 600, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Alok', 'Tewari', To_Date('1/14/1985', 'mm/dd/yyyy'), 'zaposlen', 1500, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'King', To_Date('12/12/1971', 'mm/dd/yyyy'), 'zaposlen', 600, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Andrea', 'Cirie', To_Date('8/24/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Christopher', 'Mann', To_Date('11/9/1991', 'mm/dd/yyyy'), 'zaposlen', 2000, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Kenneth', 'Israel', To_Date('10/24/1984', 'mm/dd/yyyy'), 'zaposlen', 1500, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Craig', 'Newkirk', To_Date('4/16/1970', 'mm/dd/yyyy'), 'zaposlen', 400, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Jennifer', 'Leigh Mann', To_Date('8/10/1974', 'mm/dd/yyyy'), 'zaposlen', 700, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Daniel', 'Sauli', To_Date('6/25/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Mark', 'Vincent', To_Date('10/3/1980', 'mm/dd/yyyy'), 'zaposlen', 1200, 13);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Michael', 'Garvey', To_Date('6/9/1969', 'mm/dd/yyyy'), 'zaposlen', 400, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Aaron', 'Wiggins', To_Date('5/14/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Joanna', 'Becker', To_Date('2/13/1988', 'mm/dd/yyyy'), 'zaposlen', 1700, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Victoria', 'Anastasi', To_Date('12/24/1991', 'mm/dd/yyyy'), 'zaposlen', 2000, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Mir', 'Rizvi', To_Date('11/1/1974', 'mm/dd/yyyy'), 'zaposlen', 800, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Basil', 'Kershner', To_Date('12/17/1969', 'mm/dd/yyyy'), 'zaposlen', 400, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Malcolm', 'Simmons', To_Date('2/19/1975', 'mm/dd/yyyy'), 'zaposlen', 800, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Shira', 'Bethea', To_Date('5/28/1994', 'mm/dd/yyyy'), 'zaposlen', 2200, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Gretchen', 'Koerner', To_Date('3/4/1981', 'mm/dd/yyyy'), 'zaposlen', 1200, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Sindy', 'Nurse', To_Date('9/24/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 14);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('James', 'Martinez', To_Date('1/13/1981', 'mm/dd/yyyy'), 'zaposlen', 1200, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('David', 'Clennon', To_Date('8/16/1995', 'mm/dd/yyyy'), 'zaposlen', 2300, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Murphy', 'Guyer', To_Date('9/6/1993', 'mm/dd/yyyy'), 'zaposlen', 2100, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Lance', 'Nichols', To_Date('3/24/1981', 'mm/dd/yyyy'), 'zaposlen', 1200, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('John', 'Vennema', To_Date('2/4/1965', 'mm/dd/yyyy'), 'zaposlen', 100, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Peter', 'Bradbury', To_Date('5/7/1997', 'mm/dd/yyyy'), 'zaposlen', 2400, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Marc', 'Kudisch', To_Date('4/10/1995', 'mm/dd/yyyy'), 'zaposlen', 2300, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Ellen', 'Harvey', To_Date('6/1/1987', 'mm/dd/yyyy'), 'zaposlen', 1700, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Donnie', 'Kehr', To_Date('9/19/1967', 'mm/dd/yyyy'), 'zaposlen', 200, 15);
INSERT INTO musterije(ime, prezime, datum_rodjenja, zaposlenje, mjesecna_primanja, poslovnica_id) VALUES('Albert', 'Jones', To_Date('3/21/1982', 'mm/dd/yyyy'), 'zaposlen', 1300, 15);

SELECT * FROM musterije;

COMMIT;

-- ostale tabele se pune funkcijama/procedurama

SELECT * FROM musterije;

EXECUTE otvaranje_tekuceg_racuna(2);
EXECUTE otvaranje_tekuceg_racuna(3);
EXECUTE otvaranje_tekuceg_racuna(4);
EXECUTE otvaranje_tekuceg_racuna(5);
EXECUTE otvaranje_tekuceg_racuna(6);
EXECUTE otvaranje_tekuceg_racuna(7);
EXECUTE otvaranje_tekuceg_racuna(8);
EXECUTE otvaranje_tekuceg_racuna(9);
EXECUTE otvaranje_tekuceg_racuna(10);
EXECUTE otvaranje_tekuceg_racuna(11);
EXECUTE otvaranje_tekuceg_racuna(12);
EXECUTE otvaranje_tekuceg_racuna(13);
EXECUTE otvaranje_tekuceg_racuna(14);
EXECUTE otvaranje_tekuceg_racuna(15);
EXECUTE otvaranje_tekuceg_racuna(16);
EXECUTE otvaranje_tekuceg_racuna(17);
EXECUTE otvaranje_tekuceg_racuna(18);
EXECUTE otvaranje_tekuceg_racuna(19);
EXECUTE otvaranje_tekuceg_racuna(20);
EXECUTE otvaranje_tekuceg_racuna(21);
EXECUTE otvaranje_tekuceg_racuna(22);
EXECUTE otvaranje_tekuceg_racuna(23);
EXECUTE otvaranje_tekuceg_racuna(24);
EXECUTE otvaranje_tekuceg_racuna(25);
EXECUTE otvaranje_tekuceg_racuna(26);
EXECUTE otvaranje_tekuceg_racuna(27);
EXECUTE otvaranje_tekuceg_racuna(28);
EXECUTE otvaranje_tekuceg_racuna(29);
EXECUTE otvaranje_tekuceg_racuna(30);
EXECUTE otvaranje_tekuceg_racuna(31);
EXECUTE otvaranje_tekuceg_racuna(32);
EXECUTE otvaranje_tekuceg_racuna(33);
EXECUTE otvaranje_tekuceg_racuna(34);
EXECUTE otvaranje_tekuceg_racuna(35);
EXECUTE otvaranje_tekuceg_racuna(36);
EXECUTE otvaranje_tekuceg_racuna(37);
EXECUTE otvaranje_tekuceg_racuna(38);
EXECUTE otvaranje_tekuceg_racuna(39);
EXECUTE otvaranje_tekuceg_racuna(40);
EXECUTE otvaranje_tekuceg_racuna(41);
EXECUTE otvaranje_tekuceg_racuna(42);
EXECUTE otvaranje_tekuceg_racuna(43);
EXECUTE otvaranje_tekuceg_racuna(44);
EXECUTE otvaranje_tekuceg_racuna(45);
EXECUTE otvaranje_tekuceg_racuna(46);
EXECUTE otvaranje_tekuceg_racuna(47);
EXECUTE otvaranje_tekuceg_racuna(48);
EXECUTE otvaranje_tekuceg_racuna(49);
EXECUTE otvaranje_tekuceg_racuna(50);
EXECUTE otvaranje_tekuceg_racuna(51);
EXECUTE otvaranje_tekuceg_racuna(52);
EXECUTE otvaranje_tekuceg_racuna(53);
EXECUTE otvaranje_tekuceg_racuna(54);
EXECUTE otvaranje_tekuceg_racuna(55);
EXECUTE otvaranje_tekuceg_racuna(56);
EXECUTE otvaranje_tekuceg_racuna(57);
EXECUTE otvaranje_tekuceg_racuna(58);
EXECUTE otvaranje_tekuceg_racuna(59);
EXECUTE otvaranje_tekuceg_racuna(60);
EXECUTE otvaranje_tekuceg_racuna(61);
EXECUTE otvaranje_tekuceg_racuna(62);
EXECUTE otvaranje_tekuceg_racuna(63);
EXECUTE otvaranje_tekuceg_racuna(64);
EXECUTE otvaranje_tekuceg_racuna(65);
EXECUTE otvaranje_tekuceg_racuna(66);
EXECUTE otvaranje_tekuceg_racuna(67);
EXECUTE otvaranje_tekuceg_racuna(68);
EXECUTE otvaranje_tekuceg_racuna(69);
EXECUTE otvaranje_tekuceg_racuna(70);
EXECUTE otvaranje_tekuceg_racuna(71);
EXECUTE otvaranje_tekuceg_racuna(72);
EXECUTE otvaranje_tekuceg_racuna(73);
EXECUTE otvaranje_tekuceg_racuna(74);
EXECUTE otvaranje_stednog_racuna(75);
EXECUTE otvaranje_stednog_racuna(76);
EXECUTE otvaranje_stednog_racuna(77);
EXECUTE otvaranje_stednog_racuna(78);
EXECUTE otvaranje_stednog_racuna(79);
EXECUTE otvaranje_stednog_racuna(80);
EXECUTE otvaranje_stednog_racuna(81);
EXECUTE otvaranje_stednog_racuna(82);
EXECUTE otvaranje_stednog_racuna(83);
EXECUTE otvaranje_stednog_racuna(84);
EXECUTE otvaranje_stednog_racuna(85);
EXECUTE otvaranje_stednog_racuna(86);
EXECUTE otvaranje_stednog_racuna(87);
EXECUTE otvaranje_stednog_racuna(88);
EXECUTE otvaranje_stednog_racuna(89);
EXECUTE otvaranje_stednog_racuna(90);
EXECUTE otvaranje_stednog_racuna(91);
EXECUTE otvaranje_stednog_racuna(92);
EXECUTE otvaranje_stednog_racuna(93);
EXECUTE otvaranje_stednog_racuna(94);
EXECUTE otvaranje_stednog_racuna(95);
EXECUTE otvaranje_stednog_racuna(96);
EXECUTE otvaranje_stednog_racuna(97);
EXECUTE otvaranje_stednog_racuna(98);
EXECUTE otvaranje_stednog_racuna(99);
EXECUTE otvaranje_stednog_racuna(100);
EXECUTE otvaranje_stednog_racuna(101);
EXECUTE otvaranje_stednog_racuna(102);
EXECUTE otvaranje_stednog_racuna(103);
EXECUTE otvaranje_stednog_racuna(104);
EXECUTE otvaranje_stednog_racuna(105);
EXECUTE otvaranje_stednog_racuna(106);
EXECUTE otvaranje_stednog_racuna(107);
EXECUTE otvaranje_stednog_racuna(108);
EXECUTE otvaranje_stednog_racuna(109);
EXECUTE otvaranje_stednog_racuna(110);
EXECUTE otvaranje_stednog_racuna(111);
EXECUTE otvaranje_stednog_racuna(112);
EXECUTE otvaranje_stednog_racuna(113);
EXECUTE otvaranje_stednog_racuna(114);
EXECUTE otvaranje_stednog_racuna(115);
EXECUTE otvaranje_stednog_racuna(116);
EXECUTE otvaranje_stednog_racuna(117);
EXECUTE otvaranje_stednog_racuna(118);
EXECUTE otvaranje_stednog_racuna(119);
EXECUTE otvaranje_tekuci_racun_kartica(120, 'KRED');
EXECUTE otvaranje_tekuci_racun_kartica(121, 'DEBK');
EXECUTE otvaranje_tekuci_racun_kartica(122, 'STUD');
EXECUTE otvaranje_tekuci_racun_kartica(123, 'STED');
EXECUTE otvaranje_tekuci_racun_kartica(124, 'KRED');
EXECUTE otvaranje_tekuci_racun_kartica(125, 'DEBK');
EXECUTE otvaranje_tekuci_racun_kartica(126, 'STUD');
EXECUTE otvaranje_tekuci_racun_kartica(127, 'STED');
EXECUTE otvaranje_tekuci_racun_kartica(128, 'KRED');
EXECUTE otvaranje_tekuci_racun_kartica(129, 'DEBK');
EXECUTE otvaranje_tekuci_racun_kartica(130, 'STUD');
EXECUTE otvaranje_tekuci_racun_kartica(131, 'STED');
EXECUTE otvaranje_tekuci_racun_kartica(132, 'KRED');
EXECUTE otvaranje_tekuci_racun_kartica(133, 'DEBK');
EXECUTE otvaranje_tekuci_racun_kartica(134, 'STUD');
EXECUTE otvaranje_tekuci_racun_kartica(135, 'STED');
EXECUTE otvaranje_stedni_racun_kartica(136, 'KRED');
EXECUTE otvaranje_stedni_racun_kartica(137, 'DEBK');
EXECUTE otvaranje_stedni_racun_kartica(138, 'STUD');
EXECUTE otvaranje_stedni_racun_kartica(139, 'STED');
EXECUTE otvaranje_stedni_racun_kartica(140, 'KRED');
EXECUTE otvaranje_stedni_racun_kartica(141, 'DEBK');
EXECUTE otvaranje_stedni_racun_kartica(142, 'STUD');
EXECUTE otvaranje_stedni_racun_kartica(143, 'STED');
EXECUTE otvaranje_stedni_racun_kartica(144, 'KRED');
EXECUTE otvaranje_stedni_racun_kartica(145, 'DEBK');
EXECUTE otvaranje_stedni_racun_kartica(146, 'STUD');
EXECUTE otvaranje_stedni_racun_kartica(147, 'STED');
EXECUTE otvaranje_stedni_racun_kartica(148, 'KRED');
EXECUTE otvaranje_stedni_racun_kartica(149, 'DEBK');
EXECUTE otvaranje_stedni_racun_kartica(150, 'STUD');
EXECUTE otvaranje_stedni_racun_kartica(151, 'STED');

EXECUTE polozi_pare_na_racun(380,2);
EXECUTE polozi_pare_na_racun(500,3);
EXECUTE polozi_pare_na_racun(10,4);
EXECUTE polozi_pare_na_racun(30,5);
EXECUTE polozi_pare_na_racun(600,6);
EXECUTE polozi_pare_na_racun(650,7);
EXECUTE polozi_pare_na_racun(110,8);
EXECUTE polozi_pare_na_racun(710,9);
EXECUTE polozi_pare_na_racun(900,10);
EXECUTE polozi_pare_na_racun(20,11);
EXECUTE polozi_pare_na_racun(600,12);
EXECUTE polozi_pare_na_racun(730,13);
EXECUTE polozi_pare_na_racun(630,14);
EXECUTE polozi_pare_na_racun(640,15);
EXECUTE polozi_pare_na_racun(90,16);
EXECUTE polozi_pare_na_racun(220,17);
EXECUTE polozi_pare_na_racun(230,18);
EXECUTE polozi_pare_na_racun(20,19);
EXECUTE polozi_pare_na_racun(980,20);
EXECUTE polozi_pare_na_racun(830,21);
EXECUTE polozi_pare_na_racun(460,22);
EXECUTE polozi_pare_na_racun(230,23);
EXECUTE polozi_pare_na_racun(640,24);
EXECUTE polozi_pare_na_racun(200,25);
EXECUTE polozi_pare_na_racun(330,26);
EXECUTE polozi_pare_na_racun(920,27);
EXECUTE polozi_pare_na_racun(920,28);
EXECUTE polozi_pare_na_racun(930,29);
EXECUTE polozi_pare_na_racun(560,30);
EXECUTE polozi_pare_na_racun(150,31);
EXECUTE polozi_pare_na_racun(820,32);
EXECUTE polozi_pare_na_racun(940,33);
EXECUTE polozi_pare_na_racun(940,34);
EXECUTE polozi_pare_na_racun(910,35);
EXECUTE polozi_pare_na_racun(320,36);
EXECUTE polozi_pare_na_racun(80,37);
EXECUTE polozi_pare_na_racun(750,38);
EXECUTE polozi_pare_na_racun(110,39);
EXECUTE polozi_pare_na_racun(130,40);
EXECUTE polozi_pare_na_racun(740,41);
EXECUTE polozi_pare_na_racun(160,42);
EXECUTE polozi_pare_na_racun(160,43);
EXECUTE polozi_pare_na_racun(50,44);
EXECUTE polozi_pare_na_racun(170,45);
EXECUTE polozi_pare_na_racun(40,46);
EXECUTE polozi_pare_na_racun(780,47);
EXECUTE polozi_pare_na_racun(710,48);
EXECUTE polozi_pare_na_racun(240,49);
EXECUTE polozi_pare_na_racun(310,50);
EXECUTE polozi_pare_na_racun(440,51);
EXECUTE polozi_pare_na_racun(950,52);
EXECUTE polozi_pare_na_racun(740,53);
EXECUTE polozi_pare_na_racun(270,54);
EXECUTE polozi_pare_na_racun(20,55);
EXECUTE polozi_pare_na_racun(170,56);
EXECUTE polozi_pare_na_racun(160,57);
EXECUTE polozi_pare_na_racun(850,58);
EXECUTE polozi_pare_na_racun(800,59);
EXECUTE polozi_pare_na_racun(680,60);
EXECUTE polozi_pare_na_racun(660,61);
EXECUTE polozi_pare_na_racun(720,62);
EXECUTE polozi_pare_na_racun(170,63);
EXECUTE polozi_pare_na_racun(160,64);
EXECUTE polozi_pare_na_racun(760,65);
EXECUTE polozi_pare_na_racun(180,66);
EXECUTE polozi_pare_na_racun(650,67);
EXECUTE polozi_pare_na_racun(780,68);
EXECUTE polozi_pare_na_racun(700,69);
EXECUTE polozi_pare_na_racun(330,70);
EXECUTE polozi_pare_na_racun(20,71);
EXECUTE polozi_pare_na_racun(450,72);
EXECUTE polozi_pare_na_racun(130,73);
EXECUTE polozi_pare_na_racun(870,74);
EXECUTE polozi_pare_na_racun(250,75);
EXECUTE polozi_pare_na_racun(680,76);
EXECUTE polozi_pare_na_racun(300,77);
EXECUTE polozi_pare_na_racun(180,78);
EXECUTE polozi_pare_na_racun(480,79);
EXECUTE polozi_pare_na_racun(160,80);
EXECUTE polozi_pare_na_racun(540,81);
EXECUTE polozi_pare_na_racun(220,82);
EXECUTE polozi_pare_na_racun(680,83);
EXECUTE polozi_pare_na_racun(620,84);
EXECUTE polozi_pare_na_racun(120,85);
EXECUTE polozi_pare_na_racun(180,86);
EXECUTE polozi_pare_na_racun(80,87);
EXECUTE polozi_pare_na_racun(680,88);
EXECUTE polozi_pare_na_racun(930,89);
EXECUTE polozi_pare_na_racun(750,90);
EXECUTE polozi_pare_na_racun(160,91);
EXECUTE polozi_pare_na_racun(220,92);
EXECUTE polozi_pare_na_racun(940,93);
EXECUTE polozi_pare_na_racun(410,94);
EXECUTE polozi_pare_na_racun(460,95);
EXECUTE polozi_pare_na_racun(20,96);
EXECUTE polozi_pare_na_racun(980,97);
EXECUTE polozi_pare_na_racun(10,98);
EXECUTE polozi_pare_na_racun(280,99);
EXECUTE polozi_pare_na_racun(970,100);
EXECUTE polozi_pare_na_racun(380,101);
EXECUTE polozi_pare_na_racun(10,102);
EXECUTE polozi_pare_na_racun(10,103);
EXECUTE polozi_pare_na_racun(890,104);
EXECUTE polozi_pare_na_racun(300,105);
EXECUTE polozi_pare_na_racun(970,106);
EXECUTE polozi_pare_na_racun(830,107);
EXECUTE polozi_pare_na_racun(860,108);
EXECUTE polozi_pare_na_racun(20,109);
EXECUTE polozi_pare_na_racun(320,110);
EXECUTE polozi_pare_na_racun(850,111);
EXECUTE polozi_pare_na_racun(960,112);
EXECUTE polozi_pare_na_racun(370,113);
EXECUTE polozi_pare_na_racun(640,114);
EXECUTE polozi_pare_na_racun(150,115);
EXECUTE polozi_pare_na_racun(450,116);
EXECUTE polozi_pare_na_racun(40,117);
EXECUTE polozi_pare_na_racun(530,118);
EXECUTE polozi_pare_na_racun(40,119);
EXECUTE polozi_pare_na_racun(590,120);
EXECUTE polozi_pare_na_racun(110,121);
EXECUTE polozi_pare_na_racun(950,122);
EXECUTE polozi_pare_na_racun(830,123);
EXECUTE polozi_pare_na_racun(940,124);
EXECUTE polozi_pare_na_racun(180,125);
EXECUTE polozi_pare_na_racun(780,126);
EXECUTE polozi_pare_na_racun(500,127);
EXECUTE polozi_pare_na_racun(710,128);
EXECUTE polozi_pare_na_racun(420,129);
EXECUTE polozi_pare_na_racun(230,130);
EXECUTE polozi_pare_na_racun(690,131);
EXECUTE polozi_pare_na_racun(300,132);
EXECUTE polozi_pare_na_racun(890,133);
EXECUTE polozi_pare_na_racun(500,134);
EXECUTE polozi_pare_na_racun(770,135);
EXECUTE polozi_pare_na_racun(540,136);
EXECUTE polozi_pare_na_racun(210,137);
EXECUTE polozi_pare_na_racun(770,138);
EXECUTE polozi_pare_na_racun(330,139);
EXECUTE polozi_pare_na_racun(140,140);
EXECUTE polozi_pare_na_racun(330,141);
EXECUTE polozi_pare_na_racun(210,142);
EXECUTE polozi_pare_na_racun(670,143);
EXECUTE polozi_pare_na_racun(610,144);
EXECUTE polozi_pare_na_racun(880,145);
EXECUTE polozi_pare_na_racun(190,146);
EXECUTE polozi_pare_na_racun(830,147);
EXECUTE polozi_pare_na_racun(300,148);
EXECUTE polozi_pare_na_racun(260,149);
EXECUTE polozi_pare_na_racun(10,150);
EXECUTE polozi_pare_na_racun(960,151);
EXECUTE polozi_pare_na_racun(450,152);

EXECUTE dopuni_bankomat(1, 1, 2000);
EXECUTE dopuni_bankomat(1, 4, 3000);
EXECUTE dopuni_bankomat(1, 7, 500);
EXECUTE dopuni_bankomat(1, 9, 800);
EXECUTE dopuni_bankomat(1, 11, 1000);
EXECUTE dopuni_bankomat(1, 14, 2000);

EXECUTE digni_kredit(10, 15, 'MIKRO', 1000);
EXECUTE digni_kredit(20, 25, 'MIKRO', 1000);
EXECUTE digni_kredit(30, 35, 'MIKRO', 1000);
EXECUTE digni_kredit(40, 45, 'MIKRO', 1000);
EXECUTE digni_kredit(50, 55, 'MIKRO', 1000);
EXECUTE digni_kredit(51, 56, 'HIPO', 1000);
EXECUTE digni_kredit(52, 59, 'HIPO', 1000);
EXECUTE digni_kredit(53, 90, 'HIPO', 1000);
EXECUTE digni_kredit(77, 80, 'HIPO', 1000);

EXECUTE otplata_rate_kredita(1);
EXECUTE otplata_rate_kredita(2);
EXECUTE otplata_rate_kredita(5);
EXECUTE otplata_rate_kredita(10);
EXECUTE otplata_rate_kredita(7);

COMMIT;

SELECT * FROM transakcije;
